### ISSUE TITLE
Integrazione "forzature costo dei costi del personale"

### ISSUE THREAD

**Issue by fredowashere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#100]
Come scritto da Angelica:
> da integrare su forzature costo dei costi del personale (APi fatta da valerio )

@angelicazenere riesci a dettagliare un po' meglio?
Si tratta della sostituzione dell'attuale API di forzature (che gira tuttora sul vecchio BE) con quella del nuovo BE?

**Comment by angelicazenere** [comment]
forzature costo e ricavo hanno la somma finale,
per le forzature di costo deve essere aggiunto anche il costo consuntivo che è quello che ha estratto valerio con quella api
