### ISSUE TITLE
fix mail Angelica 17/08

### ISSUE THREAD

**Issue by marcoAgugiaro** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#106]
- [x] Stato avanzamento: nel bottone cambiamo la desc Salva con "Scarica" o "Report" gestione commesse 
- [x] iniziativa non renderla obbligatoria. Aggiungere option 'Nessuno - null (o stringa vuota?)'
- [x] il cambio codice commessa è solo da lasciare ai controller e admin
- [x] in sottocommessa aggiungere la stima del costo in euro della sottocommessa (nominato come estimate at complete EAC e mappato importoCosto) 
- [x] referente cliente (mantienilo come stringa da inserire manualmente , alcune volte hanno inserito un nome probabilmente del cliente e altre del pm poi quando rientrano dalle ferie chiedo e al più come suggerimento di inserimento dalla lista dei bm+pm )
- [x] far vedere importo e stima costo nel riquadro di dettaglio della sottocommessa
- [x] prendere le nuove api di forzature  fatte da [@Valerio Cecere](mailto:valerio.cecere@grupposcai.it)  e sostituirle alle vecchie. Queste avranno dei campi in più da visualizzare (costo dipendente(costoPersonale?) per forzature costo e ricavo consuntivi(ricavoPersonale?) per forzature ricavo. Non sono due campi da gestire in inserimento perchè sono calcolati dai consuntivi, andranno mostrati solo nella lista ) e in Costi due in più da inserire (Utente e giorni).
- [x] dove sono presenti le fatture portare un nuovo tab per far vedere tutti gli incassi della commessa e lo scarico
- [x] modifica downloadFile() in utils > file.ts
- [x] in Reperibilità modificare in tabella e nel dialog di creazione "Costo reperibilità" in "Importo reperibilità"
- [x] Ordini, fatture: possibilità di visualizzare il totale al fondo (come per costi e ricavi)
- [x] Nella lista di sottocommessa sostituire 'Supporto controller' con 'Importo commessa'
- [x] In Ricavi, aggiungere totale 'Ricavo personale' nel footer
- [x] In costi rimuovere 'Totale personale' ed aggiungere 'Totale costo personale'
- [x] In commesse mandare projectManager come query parameter(idReferente) e non nel where(va rimossa)
- [x] In Incassi collegare 'scadenzaPagataNetta' alla voce della lista 'Importo'
- [x]  In Incassi: possibilità di visualizzare il totale al fondo (come per costi e ricavi)

**Comment by techUserItec** [comment]
@marcoAgugiaro 
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/108872120/306dff21-48d4-4d83-afc3-02f067656c51)
ce n'è bisogno anche in ricavo di questi due campi aggiuntivi
