### ISSUE TITLE
recupero dati sotto commessa

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#11]
per recuperarli non hai nulla? serve un endpoint?
![image](https://user-images.githubusercontent.com/10559917/236031931-46ec645f-f31f-45a0-955d-268bc004165d.png)

**Comment by fredowashere** [comment]
Devo capire perché non va... Non riesco a settare il dato, va in errore 500. Devo capire com'è stata pensata la cosa
