### ISSUE TITLE
iniziativa

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#12]
perdonami , forse sbaglio io qualcosa come faccio ad utilizzare iniziativa?modificarlo

![image](https://user-images.githubusercontent.com/10559917/236032744-79ecde48-4c8f-4ab6-9843-6f91f1fb9a67.png)

**Comment by angelicazenere** [comment]
![image](https://user-images.githubusercontent.com/10559917/236033398-196905e5-4310-418c-8cd5-b7d6580537aa.png)

**Comment by angelicazenere** [comment]
trovato dove si attiva. allora mi metteresti una piccola descrizione sopra "non attivo perchè..."

**Comment by fredowashere** [comment]
Certo... Metto un explainer text subito sotto al campo

**Comment by fredowashere** [comment]
@angelicazenere cosa dovrei scrivere?

**Comment by fredowashere** [comment]
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/5e589461-e84e-4555-98af-3ba33140bc38)
