### ISSUE TITLE
modifiche attività 

### ISSUE THREAD

**Issue by techUserItec** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#132]
- [x] copia e incolla del nome (codice?) documento che si trova in offerta
- [x] sommare fatture e ordini solo se hanno tipo "valida"
- [x] abilitare ricavi e costi anche quando c'è almeno una sotto commessa oltre che data offerta (l'unica abilitazione attuale)
- [x] #133
- [x] sezione tariffe inserire l'informazione sulla lista se è annullata o  meno 
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/108872120/de47f768-4dc5-4a26-91c7-9f077cf1fdea)
- [x] sostituire verso nuova api 
get  /modulo-attivita-be/fatture/by-commessa/id/${idCommessa}` (be scaiportal) con  GET /fatture/azienda/{idAzienda} (be modulo attività) e pure il get per il download dell'excel

**Comment by marcoAgugiaro** [comment]
@techUserItec "sezione tariffe inserire l'informazione sulla lista se è annullata o meno": la voce "Stato" indica già se è valido o meno. Nella response non vedo altre proprietà a cui fare riferimento. Sapresti darmi qualche info in più dettagliata?

**Comment by marcoAgugiaro** [comment]
L'informazione è già presente.. cosa intendi per 'evidenziare'? Non risulta già abbastanza visibile?

**Comment by marcoAgugiaro** [comment]
@techUserItec "abilitare ricavi e costi anche quando c'è almeno una sotto commessa oltre che data offerta (l'unica abilitazione attuale)" al momento l'unica condizione per l'abilitazione è che siano presenti sottocommesse. Non c'è traccia di alcuna verifica di data offerta. Da come è stata scritta sembra che dovesse essere implementato il controllo sulla presenza di sottocommesse.. Riusciresti a darmi indicazioni più chiare in merito?
