### ISSUE TITLE
gestire i dati delle statistiche di commessa

### ISSUE THREAD

**Issue by techUserItec** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#136]
ogni commessa riportare una tab che dovrà tenere solo  in visualizzazione dei dati  e la possibilità di estrarre un excel

`Sarebbe importante includere nella schermata Commessa (o Sottocommessa) del modulo Attività (e nelle reportistiche PIANO) dei campi che riportino il budget di commessa\sottocomeessa, ossia esplicitare i COSTI INTERNi e ESTERNI PREVENTIVATI, con relativa marginalità presunta (Importo contratto-tot costi previsti). In sostanza sarebbero 5 campi aggiuntivi (COSTI INTERNI, COSTI ESTERNI, COSTI TOTALI, MARGINE PREVISTO, MARGINE % PREVISTO). `

COSTI INTERNI, -> ForzatureCostiPersonale
COSTI ESTERNI, -> ForzaturaCostiIndustriali
COSTI TOTALI,  -> CostoTotale
MARGINE PREVISTO, -> ErogatoTotale - CostoTotale
MARGINE % PREVISTO -> percMargine

e altre statistiche di commessa 

le statistiche commessa che dovranno essere mostrate sono :
filtri -> idcommessa e categoria:Enum-Commessa(1)
dati da vedere : 

iniziativa
giorniPrevisti
giorniErogati
importoOfferta
fatturatoAttivo
incassato
avanzamentoSottocommessaPerc
erogatoTotale
costoTotale
percMargine
ricaviDaConsuntivi
ricaviDaForzature
costiDaForzature

con costi che deve dare anche i dettagli di 

-   frozatureCostiPersonale (costi interni )
-   forzaturaCostiIndustriali (costi esterni )
-   forzaturaCostiIndiretti
--
- costoCategoriaConsulenza
- costoCategoriaProgetto
- costoCategoriaServizio
- costoCategoriaLicenza
- costoCategoriaTicket
- costoCategoriaTrasferte
- costoCategoriaReperibilita
- costoCategoriaProdottiHardware
- costoCategoriaAuto
- costoCategoriaLogistica
- costoCategoriaManutenzione

questi sono due blocchi che sommati  in dipendentemente danno il totale forzature costo. quando stai trattando la cosa sentiamoci

aggiunta nuova voce menù
- in più predisporre nuova voce menù che in base ai filtri nell'excel tab 3 (filtri) che allego estragga un excel

https://docs.google.com/spreadsheets/d/1z2ZDbG3BTyUN-m2jKOTRcJhZS6eV_mAH/edit#gid=1484183945

- per incassi 
/incass/azienda/{idAzienda:int}/incassi/xls
- per fatture e ordini 
/fatture/azienda/{idAzienda}/xls

### primo riquadro

**prima riga:**
iniziativa / giorni previsti / giorni erogati / giorni residui (calcolati) 

**Seconda riga:**
importi offerta / ordinato / fatturato / incassato

**terza riga:**
% avanzamento (calcolo: tot erogato / imp offerta) / totale erogato / totale costi / % margine

**quarta riga:**
 Budget costi / stima a finire costi / % scostamento (stima a finire / budget costi) / backlog

### riquadro aggiuntivo

aggiungi un riquadro con i dati di sottocommessa (tante righe quante sono le sottocommesse) 

sottocommessa / ricavi totali / costi  totali / % margine

**Comment by marcoAgugiaro** [comment]
@techUserItec i punti "per incassi" e "per fatture" perchè sono presenti in questa issue? a cosa fanno riferimento?

**Comment by techUserItec** [comment]
Perché serve l'estrazione in excel globale per i due punti senza filtro per commessa

**Comment by marcoAgugiaro** [comment]
@techUserItec "In sostanza sarebbero 5 campi aggiuntivi (COSTI INTERNI, COSTI ESTERNI, COSTI TOTALI, MARGINE PREVISTO, MARGINE % PREVISTO)." questi cinque campi da dove dovrebbero essere presi? Dov'è possibile trovarli?
