### ISSUE TITLE
gironi previsti 

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#14]
non trovo la possibilità di gestire i giorni previsti per le commesse e sottocommesse

![image](https://user-images.githubusercontent.com/10559917/236037591-c8f7a639-8276-4127-bec6-704cc7a92441.png)

**Comment by fredowashere** [comment]
Bisogna aggiungerlo ai vari dialog, il problema è che non persiste quel dato, ecco il motivo per cui non l'ho messo.

**Comment by fredowashere** [comment]
Questa la mettiamo da parte, quando rifaremo gli endpoint e supporteranno la persistenza del dato aggiungeremo

**Comment by fredowashere** [comment]
Fatto read-only
