### ISSUE TITLE
assegnazione date

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#15]
guarda il tuo nomimativo @fredowashere  
aggiungere il controllo delle date nella selezione
![image](https://user-images.githubusercontent.com/10559917/236039394-082d4cf0-2d26-4d15-a472-b1c2103516ca.png)

**Comment by angelicazenere** [comment]
questo vale un pò per tutte le date inizio fine , anche task 
appunto l'ho messa manualmente

**Comment by fredowashere** [comment]
Fatto
