### ISSUE TITLE
Feature request: Aggiunta modulo Diarie

### ISSUE THREAD

**Issue by fredowashere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#21]
Il nuovo modulo dovrà contenere 3 pagine:
1. Creazione tipo trasferta;
2. Abilitazione diaria azienda;
3. Diarie permanenti ad utente.

Lo stile delle pagine è il classico "tabella CRUD" simile all'esempio seguente:
![table crud](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/8ae3a1a4-049c-495a-831e-f7f313b7971d)
[App table - Full optional](https://fredowashere.github.io/multilayout-webapp/dashboard/demos/app-table#crud)

Lo schema di analisi delle feature in oggetto è il seguente:
![Feature straord  reperib  (1)](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/8086864b-1128-497b-a4f6-6eeb5ebba9a6)

Gli endpoint da utilizzare si trovano all'indirizzo, e sono i seguenti [Swagger - Modulo Attività](https://modulo-attivita-be-dot-itec-be-project-4.ew.r.appspot.com/swagger/index.html:)
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/7073c0b6-6f86-48ba-b6c0-e2c9d05a973a)

**Comment by fredowashere** [comment]
@marcoAgugiaro con questo sviluppo a che punto siamo?

**Comment by marcoAgugiaro** [comment]
@fredowashere come ti ho anticipato ieri, sto concludendo la creazione dell'abilitazione diaria azienda
