### ISSUE TITLE
suggerimento nuova riga

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#24]
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/10559917/d98e6c7b-6cbf-4ebc-986b-77c1b018d276)
suggerisce ancora maggio anche se siamo arrivati al 100%

**Comment by fredowashere** [comment]
Cosa deve succedere?

**Comment by angelicazenere** [comment]
che non deve esporre il suggerimento del 05/2023  a zero

**Comment by fredowashere** [comment]
Allora tolgo la riga implicita quando il primo calcolo totale somma a 100%

**Comment by fredowashere** [comment]
La riga autogenerata viene aggiunta solo se c'è della percentuale rimanente residua.

![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/72a127e4-f710-465d-af44-6c3d3dab7b51)

**Comment by fredowashere** [comment]
@angelicazenere questa è da chiudere se risolta
