### ISSUE TITLE
aggiunta dei campi a livello commessa

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#25]
i campi CostoCompetenza e Importo campo sotto sottocommessa
aggiunta totale a livello commessa e cumulato a livello del mese sostituendoli agli esistenti

**Comment by fredowashere** [comment]
Se negli endpoint sono presenti le aggiungo

**Comment by angelicazenere** [comment]
si sono presenti

**Comment by fredowashere** [comment]
Allora aggiungo

**Comment by fredowashere** [comment]
@angelicazenere è in PR, se risolve chiudi la issue perfavore
