### ISSUE TITLE
suggerimento mese

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#26]
quando filtrato il mese aprile inserire come suggerimento aprile e non maggio
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/10559917/12f820a0-287f-4a59-8774-4983ff70adca)

**Comment by fredowashere** [comment]
> quando filtrato il mese aprile inserire come suggerimento aprile e non maggio

Cosa intendi dire? Che uno sceglie maggio e mandiamo alla ricerca aprile?

**Comment by fredowashere** [comment]
Ho messo il mese di default a quello corrente

**Comment by fredowashere** [comment]
@angelicazenere in PR

**Comment by fredowashere** [comment]
@angelicazenere questa è da chiudere se risolta
