### ISSUE TITLE
dove ci sono inserimenti manuali mettere una x per la cancellazione

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#27]

**Comment by fredowashere** [comment]
Inserimenti manuali di?

**Comment by angelicazenere** [comment]
tutti avanzamento e attività

**Comment by fredowashere** [comment]
Ma dove? Negli input o nelle tabelle al posto del cestino?

**Comment by fredowashere** [comment]
OK

**Comment by fredowashere** [comment]
input text, input password, input textarea e input autocomplete

**Comment by fredowashere** [comment]
Caveat: gli autocomplete di fatto sono popolati solo dopo la selezione, quindi la X salta fuori solo dopo che l'utente ha pigiato su una selezione

**Comment by fredowashere** [comment]
@angelicazenere in PR

**Comment by fredowashere** [comment]
@angelicazenere questa è da chiudere se risolta

**Comment by angelicazenere** [comment]
mancano nel modulo di attività

**Comment by fredowashere** [comment]
### Stato avanzamento:
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/dcbe02fa-04cf-4898-834d-400db6e3234e)

### Modulo attività:
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/ebd35498-62c8-4013-9ae5-f8b80342ce02)

### NOTA BENE:
`Caveat: gli autocomplete di fatto sono popolati solo dopo la selezione, quindi la X salta fuori solo dopo che l'utente ha pigiato su una selezione`
