### ISSUE TITLE
gestione errore degli endpoint

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#28]
/stato-avanzamento/azienda/15/get-sotto-commesse-avanzamento

**Comment by fredowashere** [comment]
Cosa intendi?

**Comment by fredowashere** [comment]
Non è vero, se va in errore la ricerca (che non dovrebbe in nessuna istanza ponderata) allora si blocca la ricerca, è abbastanza ovvio. Se mi dici cosa deve fare allora introduco l'errore handling. Va in 500, cosa ti aspetti? haha

**Comment by angelicazenere** [comment]
che puoi rifare l'azione. se quell'endpoint va in errore si blocca tutto e non posso fare altre cose se non con un refresh

**Comment by fredowashere** [comment]
OK, basta saperlo, in ogni caso se va in 500 non rifai nulla... Anzi, se la macchina è in uno stato di incoerenza sarebbe quasi meglio il comportamento di default. Puoi dirmi il tipo di errore che ti dà?

**Comment by fredowashere** [comment]
@marcoAgugiaro riesci ad aggiungere un catchError alla pipeline di ricerca e mostrare un toast rosso con un messaggio arbitrario "Non è stato possibile recuperare i dati. Contattare il supporto tecnico." e mandi avanti NEVER.
