### ISSUE TITLE
cambiamenti urgenti

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#33]
- [x] percentuale come numero intero (fe)
- [x] invertire stato e stato avanzamento come filtri ma non come nomi  (fe)
- [x] il titolo in stato  in dettaglio mensile è sballato - manca costo (fe)
- [x] invertire costo ricavo a livello del mese (fe)
- [x] ricavo negativo portarlo come negativo (be)
- [x] aggiungere il vistato per i'amministratore  (fe)
- [ ] mettere avviso se ci sono filtri a aperto o chiuso  (fe)
- [x] percentuale come numero intero  (fe)
- [x] forzatura inserimento a mano non accettato oltre al 100% - box rosso !  (fe)

**Comment by angelicazenere** [comment]
@fredowashere  @marcoAgugiaro le vedete perfavore? sono direttive dal cliente dirette e senza possibilità di cambiare punto di vista

**Comment by fredowashere** [comment]
@angelicazenere prima di tutto deduplica i task plz

**Comment by fredowashere** [comment]
percentuale come numero intero (fe) **Lo mettiamo da be ad intero così non dobbiamo fare elaborazioni**
 invertire stato e stato avanzamento come filtri ma non come nomi (fe) **OK**
 il titolo in stato in dettaglio mensile è sballato - manca costo (fe) **Sistemo**
 invertire costo ricavo a livello del mese (fe) **OK, stesso ordine anche a livello di dettaglio**
 ricavo negativo portarlo come negativo (be) **Che cos'è?**
 aggiungere il vistato per i'amministratore (fe) **Cosa significa? Che deve avere gli stessi privilegi del BM?**
 mettere avviso se ci sono filtri a aperto o chiuso (fe) **Cosa significa?**
 percentuale come numero intero (fe) **L'hai già scritto**
 forzatura inserimento a mano non accettato oltre al 100% - box rosso ! (fe) **L'ho già sistemato due volte, c'è qualcosa nei casi che rompe la fix... Mandami un caso che riproduca**

**Comment by angelicazenere** [comment]
percentuale come numero intero (fe) Lo mettiamo da be ad intero così non dobbiamo fare elaborazioni
invertire stato e stato avanzamento come filtri ma non come nomi (fe) OK
il titolo in stato in dettaglio mensile è sballato - manca costo (fe) Sistemo
invertire costo ricavo a livello del mese (fe) OK, stesso ordine anche a livello di dettaglio **(si portare con lo stesso ordine)**
ricavo negativo portarlo come negativo (be) Che cos'è? **(appunto per me )**
aggiungere il vistato per i'amministratore (fe) Cosa significa? Che deve avere gli stessi privilegi del BM? **(si)**
mettere avviso se ci sono filtri a aperto o chiuso (fe) Cosa significa? **(quando modifichi qualcosa che può arrivare al 100% portare un allert)**
percentuale come numero intero (fe) L'hai già scritto **copia incolla sbagliato**
forzatura inserimento a mano non accettato oltre al 100% - box rosso ! (fe) L'ho già sistemato due volte, c'è qualcosa nei casi che rompe la fix... Mandami un caso che riproduca **qualsiasi inserendo con il tastierino **

**Comment by fredowashere** [comment]
> mettere avviso se ci sono filtri a aperto o chiuso (fe)
Quando devo mettere questo avvisto? Quando il totale arriva al 100%??? Solo dopo il salvataggio o anche prima?

**Comment by fredowashere** [comment]
@angelicazenere questa è da chiudere se risolta

**Comment by angelicazenere** [comment]
mettere avviso se ci sono filtri a aperto o chiuso (fe)
-> a meno dell'ultimo commit non è presente questo comportamento 
la logica è , cambio una percentuale, la percentuale totale è maggiore o uguale al 100% e ci sono dei filtri attivi che riguardano lo stato   allora porto l'avviso

**Comment by fredowashere** [comment]
> la logica è , cambio una percentuale, la percentuale totale è maggiore o uguale al 100% e ci sono dei filtri attivi che riguardano lo stato allora porto l'avviso

Quindi se la form è sporca? O se sono sporchi solo i campi di stato? E che senso ha?
