### ISSUE TITLE
aggiornamento usabilità

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#40]
- [x] modulo gestione diarie : abilitarlo solo ad hr , segreteria , amministratore e controller
- [x] "Gestione Abilitazione Diaria Azienda" farlo solo per l'azienda loggata
- [x] mi metti anche lo stato scritto attiva /disattiva
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/10559917/2b2868a8-d878-48c0-93d6-569bfa4e69c2)

- [ ] #41
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/10559917/fa347796-40d1-45f2-83c9-f33ba90b3ee6)

.. appena riesco continuo

**Comment by marcoAgugiaro** [comment]
@angelicazenere al punto 2 "Gestione Abilitazione Diaria Azienda" farlo solo per l'azienda loggata intendi dire che bisogna mostrare in tabella i records relativi esclusivamente all'azienda con cui ci si è loggati?

**Comment by angelicazenere** [comment]
> n tabella i records relativi esclusivamente all'azienda con cui ci si è log

si

**Comment by fredowashere** [comment]
@angelicazenere se quando scrivevi
```
abilitazione straordinari e reperibilita (vediamo le APi) possiamo gestirla come delle diarie o creare un modulo a parte dove per un utente vedi tutto ciò a cui è collegato -> lista di attività/commesse, attivazioni straordinari /reperibilità e diarie attivate per commessa
```
intendevi una nuova feature allora andrebbe messa nella sua issue e gestita da un altro branch e un'altra PR.
