### ISSUE TITLE
mancata compilazione campi 

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#46]
sopra bm  e pm sono compilati , sotto no 
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/10559917/05ad5895-d840-4afe-b31a-26a4f4fd0163)

**Comment by angelicazenere** [comment]
Azienda finance e codice commessa si vede ma ho notato che lo fa per tutti o quasi .

**Comment by fredowashere** [comment]
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/2f61222b-7b04-416c-bf51-bc4a4858a3f5)
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/023d45c0-7b71-4a4c-9c43-9d4d88dcf892)
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/0c46c9c8-f881-4671-a4d1-c5e6cd6d8662)
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/41016957-7dc8-4862-84e2-1687cee747d7)

Ho preso a campione un parecchi esempi in ITEC e non un singolo caso ha un dato mancante.
In Finance invece mancano in parecchi. Questo perché nella lista utenti della get non vedo ad esempio Menardi Paolo.

**Comment by fredowashere** [comment]
Passo ad usare un altra sorgente per il dato, ma mi aspetterei i PM e BM di trovarli quando chiamo utenti senza flag

**Comment by fredowashere** [comment]
@angelicazenere qui sono letteralmente cambiati gli endpoint. Quindi direi che si può riprovare e vedere che succede!

**Comment by fredowashere** [comment]
@angelicazenere si può chiudere?
