### ISSUE TITLE
report mensile delle commesse non chiuse

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#49]
tramite una pagina unica si deve capire se ci sono persone che non hanno ancora elaborato e chiuso il mese selezionato da un menù. 
la combinazione che potrebbe essere utile dei filtri è ->tutte le persone che hanno un valore aperto nel mese selezionato x e dare la lista delle persone con le eventuali  sotto commesse

**Comment by fredowashere** [comment]
Una pagina in cui vengono listate tutte le commesse aperte in sostanza? Basta così? Magari in riga si mette BM, e innestate le sottocommesse con i PM

**Comment by angelicazenere** [comment]
si, si gestisce tranquillamente con i filtri, chiudo
