### ISSUE TITLE
Elaborazione dei dati di stato avanzamento

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#50]
Per la persona che é solo pm deve poter modificare solo la sue sottocommesse e non le altre quindi i filtri di ricerca on e bm non servono più per la persona che é solo pm

**Comment by fredowashere** [comment]
Perfetto, implemento

**Comment by fredowashere** [comment]
Ho fatto come segue: 
1) Se admin ambedue i filtri pm e bm, può fare tutto;
2) Se bm rimuovo il filtro bm ma vede il filtro pm e fisso l'idBM in chiamata al suo id utente;
3) Se pm rimuovo entrambi i filtri bm e pm, fisso idPM in chiamata al suo id utente e idBM non lo passo proprio.
