### ISSUE TITLE
aggiungere vistatura massiva

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#57]
in avanzamento commessa aggiungere seleziona tutti chiusi e vista tutti i selezionati  per scheda pm

**Comment by angelicazenere** [comment]
la vistatura massiva sarebbe dovuta essere per pm e non per sottocommessa
riusciresti a portarla a quel livello?

**Comment by fredowashere** [comment]
Certo, la metto a entrambi i livelli.

**Comment by fredowashere** [comment]
Adesso ci sono i tasti a tutti i livelli, c'è solo il problema della transizione di stato ordinata di cui scrivevo in chat.

![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/67b47811-e13e-4255-b9d6-dfffe0880e48)

**Comment by fredowashere** [comment]
@angelicazenere questa è risolutiva?

**Comment by fredowashere** [comment]
@angelicazenere si può chiudere?
