### ISSUE TITLE
modulo attività

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#61]
dove posso associare il pm nelle sotto commesse?
questo in modifica

![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/10559917/a4ce4aa1-5d1a-45ac-b16b-fd40c70e9086)

**Comment by fredowashere** [comment]
Quando integreremo le feature che mancano nel nostro nuovo applicativo (evolvendo dal vecchio) e facciamo la release FE-BE si avrà la feature richiesta.

**Comment by fredowashere** [comment]
@angelicazenere aggiungeresti il nome del campo da aggiungere nell'api di (sotto)commesse?

**Comment by fredowashere** [comment]
Con l'ultimo rilascio in COLL ho finalmente potuto constatare il corretto funzionamento di sottocommesse:

![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/f018dd15-c58d-4f23-8073-a250345e7dae)

**Comment by fredowashere** [comment]
@angelicazenere spero oggi di poter chiudure il giro di commesse/sottocommesse, in sostanza le issue rimaste irrisolte sono 3:
1) Non è possibile al momento vedere le commesse con stato invalido (da sistemare a BE);
2) Non è possibile abilitare/disabilitare le commesse (da implementare a BE);
3) Da testare l'invio di azienda a livello di legame task-risorsa.

**Comment by angelicazenere** [comment]
3 -> non va

**Comment by fredowashere** [comment]
@angelicazenere hai la PR da provare

**Comment by fredowashere** [comment]
@angelicazenere da vedere se va, in caso positivo chiudere
