### ISSUE TITLE
modulo diarie in attività 

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#69]
converisone string in int di idAzienda

![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/10559917/aa833586-31f6-4bd7-b160-475e66267f71)

**Comment by fredowashere** [comment]
Resiliente il backend vedo...

**Comment by fredowashere** [comment]
Fatto, in PR!

**Comment by fredowashere** [comment]
@angelicazenere si può chiudere?
