### ISSUE TITLE
Bug attività 

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#71]
- [x] 1. ordinamento commessa non funziona
- [x] 2. crea ricavo, non ho capito a cosa serve ma cliccando rimane con la rotellina che gira
- [x] 3.  il campo TAG si vede solo entrando in modifica ma non in visualizzazione
- [x] 4. le sezioni costi e ricavi devono visualizzare l'importo totale dei costi e dei ricavi presenti al momento dell'interrogazione  (più eventualmente il dettaglio diviso per anno)  . Il dato è ottenibile sommando i dati dei consuntivi e  delle forzature (Supporto Piano fa già un'estrazione giornaliera con questi dati per aggiornare SCAI View, si potrebbe usare lo stesso criterio.

**Comment by fredowashere** [comment]
1. Per quale proprietà di commesse deve essere ordinato? Ci sono diversi modi di ordinare quella colonna: codice, id, descrizione...;
2. Dovrebbe funzionare, ho provato con diversi casi e si apre, dovresti farti dire esattamente quale commessa lo spacca;
3. Quello a livello di commessa? Si, non si vede nel riepilogo, lo aggiungo.
4. Non funzionava così sul vecchio, sul vecchio divide le righe con quell'algoritmo strano che spacca in giorni o mesi l'importo.

**Comment by angelicazenere** [comment]
il pm deve poter modificare i dettagli anche della sotto commessa e ad esempio assegnarle un altro pm

**Comment by angelicazenere** [comment]
@marcoAgugiaro provi a fare l'ultimo punto? dettaglio del commento sopra

**Comment by angelicazenere** [comment]
lo riapro solo per promemoria 
da integrare su forzature costo dei costi del personale (APi fatta da valerio )

**Comment by fredowashere** [comment]
@angelicazenere ho chiesto a Valerio relativamente all'API di forzature e mi ha risposto che sono stati fatti solo i costi, non è sufficiente per sostituire l'API all'app perché è un unico componente e un solo endpoint, i costi e i ricavi si distinguono per la valorizzazione della firma.

**Comment by fredowashere** [comment]
Chiudo e apro una nuova issue per gestire la feature request di cui sopra
