### ISSUE TITLE
bug attività

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#72]
- [x] 1. limitare a 2 decimali degli importi sottocommessa (vedi allegato)
- [x] 2. Circosta Salvatore sul nuovo modulo non risulta abilitato alla midifca dati (cosa che può fare sul vecchio modulo)
- [x] 3. compare nella tendina un BM (Benevenga Gerado) che in relaltà era un nostro consulente proveniente da SCAI PArtners

**Comment by angelicazenere** [comment]
il pm deve poter modificare i dettagli anche della sotto commessa e ad esempio assegnarle un altro pm

**Comment by fredowashere** [comment]
Implemento come descritto ma ritengo sia un errore in quanto il PM non ha creato la risorsa (l'ha creata il BM per lui) però in pratica può distruggerla (che equivale ad una eliminazione, di fatto).
