### ISSUE TITLE
aggiunta flag 

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#75]
in sottocommesse affianco a 
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/10559917/cfd00fdb-d8c9-4ff9-aa02-d95c2c576669)
aggiungere il campo gestione avanzamento boolean
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/10559917/fa7371d2-7a33-4abf-8cdc-5180afd490ef)

**Comment by fredowashere** [comment]
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/117639221/73e44098-ccf8-4e95-8b11-ae64aea511bc)

Nell'ultimo import che ho fatto qualche giorno fa non lo vedo, è una feature request dell'ultimo momento?

**Comment by fredowashere** [comment]
@angelicazenere fatto
