### ISSUE TITLE
importo sotto commessa

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#76]
importo torna con la virgola ma viene esposto senza

![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/10559917/84a01fe5-7b23-47e5-887e-5f14232e9d5a)

**Comment by fredowashere** [comment]
@angelicazenere sistemato, ma gli arrotondamenti in alcune API non vanno bene (ad esempio in straord. se metti x,12 ti ritorna come x,11)
