### ISSUE TITLE
sotto commessa

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#79]
![image](https://github.com/SCAI-ITEC/SCAI-Modulo-attivita-frontend/assets/10559917/59f74768-8526-436c-ba9e-b2fd826b5252)
rendere non obbligatorio supporto controller

**Comment by marcoAgugiaro** [comment]
@angelicazenere si può chiudere? era dovuto al fatto che produzione non fosse allineata?
