### ISSUE TITLE
modulo attività copia commessa

### ISSUE THREAD

**Issue by angelicazenere** [SCAI-ITEC/SCAI-Modulo-attivita-frontend#9]
per le commesse molto strutturate ci mette molto tempo uno rischia di schiacciare più volte il pulsante, mettere un loader o bloccare il pulsante

**Comment by fredowashere** [comment]
Le commesse sono troppo complicate, non che non sia possibile, ma c'è veramente tanta roba. La copia l'ho implementata per sottocommessa e task
